name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend && npm install
          cd ../backend && npm install

      - name: Run Tests
        run: |
          cd frontend && npm test
          cd ../backend && npm test

      - name: Scan Code with CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  docker-build-push:
    needs: build-test-scan
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Frontend Docker Image
        run: |
          docker build -t navin360/frontend0901:latest ./ui

      - name: Build Backend Docker Image
        run: |
          docker build -t navin360/backend0901:latest ./api

      - name: Push Frontend Docker Image
        run: |
          docker push navin360/frontend0901:latest

      - name: Push Backend Docker Image
        run: |
          docker push navin360/backend0901:latest
